name = "mp-tg-subscribeboard"
main = "work.js"
compatibility_date = "2026-01-09"

[[durable_objects.bindings]]
name = "SUBSCRIBE_BOARD"
class_name = "SubscribeBoardDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SubscribeBoardDO"]
